Repository UBC-MDS/autopredictor, pull requests merged in 2024-01, with the labels that each got.

#7 Readme func and python ecosystem
  README.md
Labels: documentation

#15 doc: renamed function name and added link
  README.md
Labels: documentation

#17 Added summary in Readme
  README.md
Labels: documentation

#13 Added bestscore.py to display best score
  src/autopredictor/bestscore.py
Labels: documentation

#8 doc: Added docstring for the show_all function
  src/autopredictor/show_all.py
Labels: documentation

#14 doc: Docstring for the select_model function
  src/autopredictor/select_model.py
Labels: documentation

#19 Added new input parameter in docstring
  src/autopredictor/bestscore.py
Labels: documentation

#11 Added fit.py
  src/autopredictor/fit.py
Labels: documentation

#32 Added all dependencies
  poetry.lock
  pyproject.toml
Labels: Code

#27 Fit function
  src/autopredictor/fit.py
  tests/test_fit.py
Labels: Code

#31 Added functionality in display_best_score function
  src/autopredictor/bestscore.py
Labels: Code

#35 Added test_bestscore
  tests/test_bestscore.py
Labels: documentation, Code

#33 Code for Select Model
  src/autopredictor/select_model.py
Labels: Code

#30 Implemented test_show_all.py
  tests/test_show_all.py
Labels: Code

#29 Code show all
  src/autopredictor/show_all.py
Labels: Code

#38 Installation instruction updated to fit current progress
  README.md
Labels: documentation

#46 Updated dependency to build html
  poetry.lock
  pyproject.toml
Labels: Code

#58 Updated Readme to include badges and logo
  README.md
Labels: documentation

#54 Example File
  docs/example.ipynb
  src/autopredictor/autopredictor.py
Labels: documentation

#61 Deleting Unused Test File
  tests/test_autopredictor.py
Labels: enhancement
