Repository UBC-MDS/autopredictor, pull requests merged in 2024-02, with the labels that each got.

#62 Added tool.semantic_release
  pyproject.toml
Labels: Code

#64 Update ci-cd.yml
  .github/workflows/ci-cd.yml
Labels: Code

#72 fix: Feedback addressed by Anu for function display_best_score
  src/autopredictor/bestscore.py
  tests/test_bestscore.py
Labels: Code

#70 Addressed Feedback: Vignette
  docs/example.ipynb
Labels: documentation

#68 Refine readme
  README.md
Labels: documentation

#75 fix: Feedback addressed by Arturo for input types
  poetry.lock
  tests/test_fit.py
Labels: enhancement

#78 feat: Feedback addressed by Anu. Change R2 values in examples
  src/autopredictor/bestscore.py
  tests/test_bestscore.py
Labels: Code

#73 Update License to GNU
  LICENSE
Labels: documentation

#81 Update ci-cd.yml
  .github/workflows/ci-cd.yml
Labels: bug, Code

#80 fix: Update CHANGELOG file for consistency
  CHANGELOG.md
Labels: documentation

#83 Update License in pyproject.toml
  pyproject.toml
Labels: Code
